### ISSUE TITLE
BEGIN failed--compilation aborted at lib/Dancer2/Plugin/Adapter.pm line 10, <DATA> line 1003.

### ISSUE THREAD

**Issue by sdeseille** [PerlDancer/dancer2-plugin-adapter#1]
Hi dagolden

I found some update to do in your module and in testfile "www-postmark.t"

I suspect that with last version of Dancer2 ':syntax' parameters became obsolete.
So to install your module I did following operations.

in file "Adapter.pm"
I substituted
use Dancer2 ':syntax'; 
with
use Dancer2;

in file "www-postmark.t"
I did the same thing as with "Adapter.pm"

And then ....
D:\myperl\data.cpanm\work\1378982950.5272\Dancer2-Plugin-Adapter-0.005>cpanm .
--> Working on .
Configuring Dancer2-Plugin-Adapter-0.005 ... OK
Building and testing Dancer2-Plugin-Adapter-0.005 ... OK
Successfully installed Dancer2-Plugin-Adapter-0.005
1 distribution installed

The version of Perl I use is following : 

---

 Welcome to Strawberry Perl Portable Edition!
- URL - http://www.strawberryperl.com/
- see README.portable.TXT for more info
  ----------------------------------------------
  Perl executable: D:\myperl\perl\bin\perl.exe
  Perl version   : 5.16.3 / MSWin32-x86-multi-thread

Regards

sdeseille

**Comment by dagolden** [comment]
Thanks.  I'll sort it out soonish.  I'm waiting on a bunch of bug fixes in Dancer2 itself to be released before I go fixing my various broken modules.
