### ISSUE TITLE
Does not work on my computer

### ISSUE THREAD

**Issue by mascip** [PerlDancer/dancer2-plugin-adapter#2]
Hi David, some tests won't pass and I don't understand them. I have tried to force install but the module just won't work. Here is the test log:

cpanm (App::cpanminus) 1.6005 on perl 5.016003 built for x86_64-linux
Work directory is /home/user/.cpanm/work/1386264493.30792
You have make /usr/bin/make
You have LWP 6.05
You have /bin/tar: tar (GNU tar) 1.23
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Dancer2::Plugin::Adapter on cpanmetadb ...
--> Working on Dancer2::Plugin::Adapter
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Dancer2-Plugin-Adapter-0.005.tar.gz
-> OK
Unpacking Dancer2-Plugin-Adapter-0.005.tar.gz
Entering Dancer2-Plugin-Adapter-0.005
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.30 ... Yes (6.64)
Configuring Dancer2-Plugin-Adapter-0.005
Running Makefile.PL
Checking if your kit is complete...
Looks good
Writing Makefile for Dancer2::Plugin::Adapter
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.64)
Checking if you have Test::More 0.96 ... Yes (0.98)
Checking if you have List::Util 0 ... Yes (1.25)
Checking if you have Test::TCP 0 ... Yes (2.00)
Checking if you have LWP::UserAgent 0 ... Yes (6.05)
Checking if you have File::Find 0 ... Yes (1.20)
Checking if you have File::Temp 0.19 ... Yes (0.22)
Checking if you have HTTP::Tiny 0 ... Yes (0.034)
Checking if you have File::Spec::Functions 0 ... Yes (3.40)
Checking if you have JSON 0 ... Yes (2.90)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.64)
Checking if you have Test::More 0.96 ... Yes (0.98)
Checking if you have List::Util 0 ... Yes (1.25)
Checking if you have Test::TCP 0 ... Yes (2.00)
Checking if you have LWP::UserAgent 0 ... Yes (6.05)
Checking if you have File::Find 0 ... Yes (1.20)
Checking if you have File::Temp 0.19 ... Yes (0.22)
Checking if you have HTTP::Tiny 0 ... Yes (0.034)
Checking if you have File::Spec::Functions 0 ... Yes (3.40)
Checking if you have JSON 0 ... Yes (2.90)
Checking if you have warnings 0 ... Yes (1.13)
Checking if you have strict 0 ... Yes (1.07)
Checking if you have Dancer2 0 ... Yes (0.10)
Checking if you have Class::Load 0 ... Yes (0.20)
Checking if you have Dancer2::Plugin 0 ... Yes (0.10)
Building and testing Dancer2-Plugin-Adapter-0.005
cp lib/Dancer2/Plugin/Adapter.pm blib/lib/Dancer2/Plugin/Adapter.pm
Manifying blib/man3/Dancer2::Plugin::Adapter.3
PERL_DL_NONLAZY=1 /home/user/perl5/perlbrew/perls/perl-5.16.3/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
parameters to 'use Dancer2' should be one of : 'key => value', ':script', or !<keyword>, where <keyword> is a DSL keyword you don't want to import at /home/user/.perlbrew/libs/perl-5.16.3@devel/lib/perl5/Dancer2.pm line 52, <DATA> line 1003.
BEGIN failed--compilation aborted at lib/Dancer2/Plugin/Adapter.pm line 10, <DATA> line 1003.
Compilation failed in require at -e line 1, <DATA> line 1003.
# Failed test 'Dancer2::Plugin::Adapter loaded ok'
# at t/00-compile.t line 62.
# ''
# doesn't match '(?^s:^\s*Dancer2::Plugin::Adapter ok)'
# Looks like you failed 1 test of 1.

t/00-compile.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
# Prerequisite Report:
# Version Module
# ------- ---------------------
#0.20 Class::Load
#0.06 Class::Load::XS
#0.10 Dancer2
#0.10 Dancer2::Plugin
#6.64 ExtUtils::MakeMaker
#1.20 File::Find
#3.40 File::Spec::Functions
#0.22 File::Temp
#0.034 HTTP::Tiny
#2.90 JSON
#6.05 LWP::UserAgent
#1.25 List::Util
#0.98 Test::More
#2.00 Test::TCP
# missing WWW::Postmark
#1.07 strict
#1.13 warnings

t/00-report-prereqs.t .. ok
parameters to 'use Dancer2' should be one of : 'key => value', ':script', or !<keyword>, where <keyword> is a DSL keyword you don't want to import at /home/user/.perlbrew/libs/perl-5.16.3@devel/lib/perl5/Dancer2.pm line 52.
BEGIN failed--compilation aborted at /home/user/.cpanm/work/1386264493.30792/Dancer2-Plugin-Adapter-0.005/blib/lib/Dancer2/Plugin/Adapter.pm line 10.
Compilation failed in require at t/file-temp.t line 22.
BEGIN failed--compilation aborted at t/file-temp.t line 22.
t/file-temp.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
parameters to 'use Dancer2' should be one of : 'key => value', ':script', or !<keyword>, where <keyword> is a DSL keyword you don't want to import at /home/user/.perlbrew/libs/perl-5.16.3@devel/lib/perl5/Dancer2.pm line 52.
BEGIN failed--compilation aborted at /home/user/.cpanm/work/1386264493.30792/Dancer2-Plugin-Adapter-0.005/blib/lib/Dancer2/Plugin/Adapter.pm line 10.
Compilation failed in require at t/http-tiny.t line 23.
BEGIN failed--compilation aborted at t/http-tiny.t line 23.
t/http-tiny.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
parameters to 'use Dancer2' should be one of : 'key => value', ':script', or !<keyword>, where <keyword> is a DSL keyword you don't want to import at /home/user/.perlbrew/libs/perl-5.16.3@devel/lib/perl5/Dancer2.pm line 52.
BEGIN failed--compilation aborted at /home/user/.cpanm/work/1386264493.30792/Dancer2-Plugin-Adapter-0.005/blib/lib/Dancer2/Plugin/Adapter.pm line 10.
Compilation failed in require at t/scopes.t line 49.
BEGIN failed--compilation aborted at t/scopes.t line 49.
t/scopes.t ............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
parameters to 'use Dancer2' should be one of : 'key => value', ':script', or !<keyword>, where <keyword> is a DSL keyword you don't want to import at /home/user/.perlbrew/libs/perl-5.16.3@devel/lib/perl5/Dancer2.pm line 52, <DATA> line 1003.
BEGIN failed--compilation aborted at t/www-postmark.t line 27, <DATA> line 1003.
t/www-postmark.t ....... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
## Test Summary Report

t/00-compile.t       (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/file-temp.t        (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/http-tiny.t        (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/scopes.t           (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/www-postmark.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=6, Tests=2,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.88 cusr  0.08 csys =  0.99 CPU)
Result: FAIL
Failed 5/6 test programs. 1/2 subtests failed.
make: **\* [test_dynamic] Error 255
-> FAIL Installing Dancer2::Plugin::Adapter failed. See /home/user/.cpanm/build.log for details.

**Comment by dagolden** [comment]
Dancer2 is unstable and I'm not bothering to fix things until it is.  Sorry about that.

**Comment by mascip** [comment]
I understand :-)

Any idea of an alternative way to declare a singleton for my app?

--- Pierre Masci
I check email a couple times daily; to reach me sooner, you can send me a
text message via this page: https://awayfind.com/mascip

**Comment by yanick** [comment]
The new release should take care of this.
